front-shop:
  component: '@sls-next/serverless-component@1.17.0-alpha.13'
  inputs:
    description: 'Bottle House - Front Shop SSR'
    bucketName: ${env.BUCKET_NAME}
    cloudfront:
      distributionId: ${env.DISTRIBUTION_ID}
