name: Front Shop Pipeline

on:
  push:
    branches: [dev]
    paths:
      - 'packages/front-shop/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Build
        run: yarn build:front-shop:staging
      - name: Deploy Shop
        working-directory: ./packages/front-shop
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          mv .env.staging .env
          serverless --stage=staging
